spring:
  application:
    name: eggpop-backend

  profiles:
    active: ${SPRING_PROFILES_ACTIVE}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  flyway:
    enabled: ${FLYWAY_ENABLED}
    baseline-on-migrate: true

  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true